service: coin-price-prediction

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    COINGECKO_API_KEY: 'CG-sou5TJWDNdLnDCbWMTPyi6bT'
  
functions:
  predictPrice:
    handler: functions/predictPrice.handler
    memorySize: 1024
    timeout: 30
    events:
      - http:
          path: predict
          method: post
          cors: true

  getHistoricalData:
    handler: functions/getHistoricalData.handler
    memorySize: 512
    timeout: 30
    events:
      - http:
          path: historical/{coinId}
          method: get
          cors: true
          request:
            parameters:
              paths:
                coinId: true

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true
  serverless-offline:
    httpPort: 4000